services:
  tourism-app:
    build: .
    image: smart-tourism-portal:1.0.0
    ports:
      - "8085:8085"
    restart: unless-stopped
  graphite:
    image: graphiteapp/graphite-statsd:latest
    ports:
      - "8081:80"
      - "2003:2003"
      - "8125:8125/udp"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning


  nagios:
    image: jasonrivers/nagios:latest
    container_name: tourism-nagios
    ports:
      - "8082:80"
    volumes:
      - ./monitoring/nagios/smart-tourism.cfg:/opt/nagios/etc/objects/smart-tourism.cfg
