spring.application.name=smart-tourism-portal
server.port=8085
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:tourismdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true
info.app.name=Smart Tourism Information Portal
info.app.version=1.0.0
management.metrics.export.graphite.enabled=true
management.metrics.export.graphite.host=graphite
management.metrics.export.graphite.port=2003
management.metrics.export.graphite.step=10s
